import http from './http.js'

export const apiCaptcha    = o => (http.get('captcha', o))
export const apiSendSms    = o => (http.get('sendSms', o))
export const apiLogin      = o => (http.post('login', o))
export const apiSign       = o => (http.post('sign', o))
export const aaa           = o => (http.post('aaa', o))
export const apiOkex       = o => (http.post('okex', o))
export const apiPayInfo    = o => (http.post('payInfo', o))
export const apiOrderForm  = o => (http.get('orderForm', o))
// KMKAS&ASQW export const apiCheckAddr  = o => (http.get('checkAddr', o))
export const apiAuthAddr   = o => (http.post('authAddr', o))
export const apiPower      = o => (http.get('power', o))
export const apiUser       = o => (http.get('user', o))
export const apiRecord     = o => (http.get('record', o))
export const apiDelOrder   = o => (http.delete('order', o))
export const apiAsset      = o => (http.get('asset', o))
export const apiBuy        = o => (http.post('buy', o))
export const apiSell       = o => (http.post('sell', o))
export const apiCancelSell = o => (http.post('cancelSell', o))
export const apiShopList   = o => (http.get('shopList', o))
export const apiShopDetail = o => (http.get('shopDetail', o))
export const apiForget     = o => (http.post('forget', o))
